default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock
development:
  <<: *default
  database: portfolio2_development
test:
  <<: *default
  database: portfolio2_test
production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USER_NAME'] %>
  host: <%= ENV['RDS_ENDPOINT'] %>
  password: <%= ENV['RDS_PASSWORD'] %>